<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Laporan Analisis Voucher</title>
    <style>
        @page {
            margin: 1.5cm;
        }

        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 9px;
            line-height: 1.4;
            color: #1e293b;
        }

        h2 {
            margin: 0;
            padding: 0;
            font-size: 18px;
            font-weight: 700;
            color: #0f172a;
        }

        .header-container {
            width: 100%;
            margin-bottom: 20px;
            border-bottom: 2px solid #334155;
            padding-bottom: 15px;
        }

        .header-title {
            float: left;
            width: 50%;
        }

        .header-meta {
            float: right;
            width: 45%;
            text-align: right;
            font-size: 9px;
            color: #64748b;
        }

        .clear {
            clear: both;
        }

        .filters-box {
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            padding: 10px 12px;
            margin-bottom: 20px;
        }

        .filters-title {
            font-weight: bold;
            font-size: 9px;
            color: #475569;
            margin-bottom: 6px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        .filters-table {
            width: 100%;
            border-collapse: collapse;
        }

        .filters-table td {
            padding: 2px 8px 2px 0;
            font-size: 9px;
            color: #334155;
        }

        .filters-table td span {
            font-weight: 600;
        }

        /* KPI Cards Section */
        .kpi-container {
            width: 100%;
            margin-bottom: 20px;
        }

        .kpi-card {
            display: inline-block;
            width: 15.5%;
            margin-right: 1%;
            background-color: #fff;
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            padding: 8px 10px;
            box-sizing: border-box;
            vertical-align: top;
        }

        .kpi-card.last {
            margin-right: 0;
        }

        .kpi-title {
            font-size: 7.5px;
            font-weight: bold;
            text-transform: uppercase;
            color: #64748b;
            margin-bottom: 4px;
        }

        .kpi-card-value {
            font-size: 11px;
            font-weight: bold;
            color: #0f172a;
        }

        .kpi-card-value.active { color: #16a34a; }
        .kpi-card-value.used { color: #2563eb; }
        .kpi-card-value.expired { color: #d97706; }
        .kpi-card-value.void { color: #dc2626; }
        .kpi-card-value.nominal { color: #4f46e5; }

        /* Report Table Styling */
        table.report {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.report th {
            background-color: #334155;
            color: #ffffff;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 8px;
            letter-spacing: 0.5px;
            padding: 8px 6px;
            border: 1px solid #475569;
        }

        table.report td {
            border: 1px solid #e2e8f0;
            padding: 7px 6px;
            font-size: 8.5px;
            color: #334155;
            vertical-align: top;
        }

        table.report tr:nth-child(even) {
            background-color: #f8fafc;
        }

        .sub-text {
            font-size: 7.5px;
            color: #64748b;
            margin-top: 2px;
        }

        .text-right {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }

        .font-semibold {
            font-weight: 600;
        }

        .font-mono {
            font-family: Courier, monospace;
            letter-spacing: 0.5px;
        }

        .footer {
            margin-top: 30px;
            border-top: 1px solid #e2e8f0;
            padding-top: 8px;
            text-align: right;
            font-size: 8px;
            color: #94a3b8;
        }
    </style>
</head>

<body>

    <div class="header-container">
        <div class="header-title">
            <h2>Laporan Analisis Voucher</h2>
            <p style="margin: 3px 0 0 0; color: #64748b; font-size: 9.5px;">Generated by Voucher Management System</p>
        </div>
        <div class="header-meta">
            Tanggal Cetak: {{ now()->format('d M Y, H:i') }}
        </div>
        <div class="clear"></div>
    </div>

    <!-- Filters Info Box -->
    <div class="filters-box">
        <div class="filters-title">Kriteria Penyaringan Laporan</div>
        <table class="filters-table">
            <tr>
                <td width="20%">Status: <span>{{ $filters['status'] ?: 'Semua Status' }}</span></td>
                <td width="25%">Departemen: <span>{{ $filters['department'] ?: 'Semua Departemen' }}</span></td>
                <td width="25%">Lokasi Toko: <span>{{ $filters['store'] ?: 'Semua Toko' }}</span></td>
                <td width="30%">Kata Kunci: <span>{{ $filters['search'] ?: '-' }}</span></td>
            </tr>
        </table>
    </div>

    <!-- KPI Summary Section -->
    <div class="kpi-container">
        <div class="kpi-card">
            <div class="kpi-title">Total Voucher</div>
            <div class="kpi-card-value">{{ $vouchers->count() }} Lembar</div>
        </div>
        <div class="kpi-card">
            <div class="kpi-title">Total Nominal</div>
            <div class="kpi-card-value nominal">Rp {{ number_format($vouchers->sum('nominal'), 0, ',', '.') }}</div>
        </div>
        <div class="kpi-card">
            <div class="kpi-title">Aktif</div>
            <div class="kpi-card-value active">{{ $vouchers->where('status', \App\Enums\VoucherStatus::ACTIVE)->count() }} Lbr</div>
        </div>
        <div class="kpi-card">
            <div class="kpi-title">Terpakai</div>
            <div class="kpi-card-value used">{{ $vouchers->where('status', \App\Enums\VoucherStatus::USED)->count() }} Lbr</div>
        </div>
        <div class="kpi-card">
            <div class="kpi-title">Kedaluwarsa</div>
            <div class="kpi-card-value expired">{{ $vouchers->where('status', \App\Enums\VoucherStatus::EXPIRED)->count() }} Lbr</div>
        </div>
        <div class="kpi-card last">
            <div class="kpi-title">Void</div>
            <div class="kpi-card-value void">{{ $vouchers->where('status', \App\Enums\VoucherStatus::VOID)->count() }} Lbr</div>
        </div>
        <div class="clear"></div>
    </div>

    <!-- Clean Consolidated Table -->
    <table class="report">
        <thead>
            <tr>
                <th width="4%">No</th>
                <th width="12%">Kode Voucher</th>
                <th width="20%">Karyawan & Departemen</th>
                <th width="18%">Penukaran Toko (Kasir)</th>
                <th width="11%">Nominal</th>
                <th width="11%">Status</th>
                <th width="12%">Masa Berlaku</th>
                <th width="12%">Waktu Transaksi</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($vouchers as $voucher)
                <tr>
                    <td class="text-center">{{ $loop->iteration }}</td>
                    <td class="font-mono font-semibold">{{ $voucher->code }}</td>
                    <td>
                        <div class="font-semibold">{{ $voucher->employee?->name }}</div>
                        <div class="sub-text">Dept: {{ $voucher->employee?->department?->name ?? '-' }}</div>
                    </td>
                    <td>
                        @if($voucher->redemption)
                            <div class="font-semibold">{{ $voucher->redemption->store?->name ?? '-' }}</div>
                            <div class="sub-text">Kasir: {{ $voucher->redemption->cashier?->name ?? '-' }}</div>
                        @else
                            <div style="color: #94a3b8;">-</div>
                        @endif
                    </td>
                    <td class="text-right font-semibold" style="color: #4f46e5;">
                        {{ number_format($voucher->nominal, 0, ',', '.') }}
                    </td>
                    <td class="text-center">
                        <div class="font-semibold">Vcr: {{ $voucher->status->value }}</div>
                        @if($voucher->redemption?->claim_status)
                            <div class="sub-text">Klm: {{ $voucher->redemption->claim_status->value }}</div>
                        @endif
                    </td>
                    <td>
                        <div>Rilis: {{ optional($voucher->issued_at)->format('d/m/Y') }}</div>
                        <div class="sub-text">Exp: {{ optional($voucher->expired_at)->format('d/m/Y') }}</div>
                    </td>
                    <td>
                        @if($voucher->used_at)
                            <div>Tukar: {{ optional($voucher->used_at)->format('d/m/Y H:i') }}</div>
                        @endif
                        @if($voucher->redemption?->claimed_at)
                            <div class="sub-text">Klaim: {{ optional($voucher->redemption->claimed_at)->format('d/m/Y H:i') }}</div>
                        @endif
                        @if($voucher->redemption?->paid_at)
                            <div class="sub-text">Bayar: {{ optional($voucher->redemption->paid_at)->format('d/m/Y H:i') }}</div>
                        @endif
                        @if(!$voucher->used_at && !$voucher->redemption?->claimed_at && !$voucher->redemption?->paid_at)
                            <div style="color: #94a3b8;">-</div>
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Dokumen Rahasia Perusahaan
    </div>

</body>

</html>